# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_Lohmann_conv <- function(tmpm) {
    .Call('_VICmodel_aux_Lohmann_conv', PACKAGE = 'VICmodel', tmpm)
}

vic_run_cell <- function(vic_options, forcing, soil_par, snowband, veg_par, lake_par, forcing_veg, veglib, output_info) {
    .Call('_VICmodel_vic_run_cell', PACKAGE = 'VICmodel', vic_options, forcing, soil_par, snowband, veg_par, lake_par, forcing_veg, veglib, output_info)
}

#' Display version of VIC model and this package.
#'
#'
#' @export
vic_version <- function() {
    invisible(.Call('_VICmodel_vic_version', PACKAGE = 'VICmodel'))
}

